from django.contrib import admin
from upc import models

# admin.site.register(models.Question)
# admin.site.register(models.Product)
# admin.site.register(models.MachineType)
# admin.site.register(models.MixingChamberSize)
# admin.site.register(models.SprayingType)
# admin.site.register(models.AmbientTemp)
# admin.site.register(models.ASideTemp)
# admin.site.register(models.BSideTemp)
# admin.site.register(models.HoseTemp)
# admin.site.register(models.SubstrateTemp)
# admin.site.register(models.StartingDrumTemp)
# admin.site.register(models.HumidityLevel)
# admin.site.register(models.SprayingSpeed)
# admin.site.register(models.HoseTypeInsulated)
# admin.site.register(models.HoseIn)
# admin.site.register(models.SprayLayers)
# admin.site.register(models.SubstrateType)

admin.site.register(models.SprayFoamType)
admin.site.register(models.SubstrateTemp)

admin.site.register(models.SprayMachineType)
admin.site.register(models.SprayMixingChamber)
admin.site.register(models.SprayType)
admin.site.register(models.AmbientTemperature)
admin.site.register(models.SubstrateTemperature)
admin.site.register(models.BoardFeet)
admin.site.register(models.Density)
admin.site.register(models.Condition)
admin.site.register(models.StartingDrumTemperature)
admin.site.register(models.SprayHumidityLevel)
admin.site.register(models.SpeedOfSpraying)
admin.site.register(models.HoseInsulated)
admin.site.register(models.SprayHoseIn)
admin.site.register(models.Substrate)
admin.site.register(models.Layers)
admin.site.register(models.SprayingType)
admin.site.register(models.AmbientTemp)
